package com.lazyshan.oa.sms.models;

// Generated 2015-6-21 0:57:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name = "product_type", catalog = "lazyshan", uniqueConstraints = @UniqueConstraint(columnNames = "parentTypeId"))
public class ProductType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8701023629174982398L;
	private Integer typeId;
	private Date version;
	private String typeName;
	private Integer parentTypeId;
	private int typeLevel;
	private Integer position;
	private String desc;

	public ProductType() {
	}

	public ProductType(String typeName, int typeLevel) {
		this.typeName = typeName;
		this.typeLevel = typeLevel;
	}

	public ProductType(String typeName, Integer parentTypeId, int typeLevel, Integer position, String desc) {
		this.typeName = typeName;
		this.parentTypeId = parentTypeId;
		this.typeLevel = typeLevel;
		this.position = position;
		this.desc = desc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeId", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", length = 19)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "typeName", nullable = false, length = 20)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "parentTypeId", unique = true)
	public Integer getParentTypeId() {
		return this.parentTypeId;
	}

	public void setParentTypeId(Integer parentTypeId) {
		this.parentTypeId = parentTypeId;
	}

	@Column(name = "typeLevel", nullable = false)
	public int getTypeLevel() {
		return this.typeLevel;
	}

	public void setTypeLevel(int typeLevel) {
		this.typeLevel = typeLevel;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "desc", length = 45)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
