package com.lazyshan.oa.mms.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Model class of factory.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Factory implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 厂家id. */
	private Integer facotryId;

	public List<ProductSupply> getProductSupplies() {
		return productSupplies;
	}

	public void setProductSupplies(List<ProductSupply> productSupplies) {
		this.productSupplies = productSupplies;
	}

	/** 工厂名称. */
	private String factoryname;

	/** The set of 产品供应表. */
	private List<ProductSupply> productSupplies = new ArrayList<ProductSupply>();

	/**
	 * Set the 厂家id.
	 * 
	 * @param facotryId
	 *            厂家id
	 */
	public void setFacotryId(Integer facotryId) {
		this.facotryId = facotryId;
	}

	/**
	 * Get the 厂家id.
	 * 
	 * @return 厂家id
	 */
	public Integer getFacotryId() {
		return this.facotryId;
	}

	/**
	 * Set the 工厂名称.
	 * 
	 * @param factoryname
	 *            工厂名称
	 */
	public void setFactoryname(String factoryname) {
		this.factoryname = factoryname;
	}

	/**
	 * Get the 工厂名称.
	 * 
	 * @return 工厂名称
	 */
	public String getFactoryname() {
		return this.factoryname;
	}

	/**
	 * Add the 产品供应表.
	 * 
	 * @param productSupply
	 *            产品供应表
	 */
	public void addProductSupply(ProductSupply productSupply) {
		this.productSupplies.add(productSupply);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Factory other = (Factory) obj;
		if (facotryId == null) {
			if (other.facotryId != null) {
				return false;
			}
		} else if (!facotryId.equals(other.facotryId)) {
			return false;
		}
		return true;
	}

}
