package com.lazyshan.oa.mms.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Model class of 产品规格表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProductSpec implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 产品规格. */
	private Integer productSpec;

	/** 产品规格名称. */
	private String productSpecName;

	/** 描述. */
	private String productSpecDesc;

	/** product. */
	private Product product;

	/** The set of 产品供应表. */
	private List<ProductSupply> productSupplies = new ArrayList<>();

	public List<ProductSupply> getProductSupplies() {
		return productSupplies;
	}

	public void setProductSupplies(List<ProductSupply> productSupplies) {
		this.productSupplies = productSupplies;
	}

	/**
	 * Set the 产品规格.
	 * 
	 * @param productSpec
	 *            产品规格
	 */
	public void setProductSpec(Integer productSpec) {
		this.productSpec = productSpec;
	}

	/**
	 * Get the 产品规格.
	 * 
	 * @return 产品规格
	 */
	public Integer getProductSpec() {
		return this.productSpec;
	}

	/**
	 * Set the 产品规格名称.
	 * 
	 * @param productSpecName
	 *            产品规格名称
	 */
	public void setProductSpecName(String productSpecName) {
		this.productSpecName = productSpecName;
	}

	/**
	 * Get the 产品规格名称.
	 * 
	 * @return 产品规格名称
	 */
	public String getProductSpecName() {
		return this.productSpecName;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param productSpecDesc
	 *            描述
	 */
	public void setProductSpecDesc(String productSpecDesc) {
		this.productSpecDesc = productSpecDesc;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getProductSpecDesc() {
		return this.productSpecDesc;
	}

	/**
	 * Set the product.
	 * 
	 * @param product
	 *            product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the product.
	 * 
	 * @return product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Add the 产品供应表.
	 * 
	 * @param productSupply
	 *            产品供应表
	 */
	public void addProductSupply(ProductSupply productSupply) {
		this.productSupplies.add(productSupply);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productSpec == null) ? 0 : productSpec.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProductSpec other = (ProductSpec) obj;
		if (productSpec == null) {
			if (other.productSpec != null) {
				return false;
			}
		} else if (!productSpec.equals(other.productSpec)) {
			return false;
		}
		return true;
	}

}
