package com.lazyshan.oa.mms.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Model class of 产品类型表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProductType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 产品类型id. */
	private Integer productType;

	/** 产品类型名称. */
	private String productTypeDesc;
	/**
	 * 类目下产品数量
	 */
	private int productCount;

	public int getProductCount() {
		return productCount;
	}

	public void setProductCount(int productCount) {
		this.productCount = productCount;
	}

	/**
	 * Set the 产品类型id.
	 * 
	 * @param productType
	 *            产品类型id
	 */
	public void setProductType(Integer productType) {
		this.productType = productType;
	}

	/**
	 * Get the 产品类型id.
	 * 
	 * @return 产品类型id
	 */
	public Integer getProductType() {
		return this.productType;
	}

	/**
	 * Set the 产品类型名称.
	 * 
	 * @param productTypeDesc
	 *            产品类型名称
	 */
	public void setProductTypeDesc(String productTypeDesc) {
		this.productTypeDesc = productTypeDesc;
	}

	/**
	 * Get the 产品类型名称.
	 * 
	 * @return 产品类型名称
	 */
	public String getProductTypeDesc() {
		return this.productTypeDesc;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productType == null) ? 0 : productType.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProductType other = (ProductType) obj;
		if (productType == null) {
			if (other.productType != null) {
				return false;
			}
		} else if (!productType.equals(other.productType)) {
			return false;
		}
		return true;
	}

}
