package com.lazyshan.oa.mms.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Model class of product.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 产品型号. */
	private String productModel;

	/** 产品类型表. */
	private ProductType productType;

	/** 产品名称. */
	private String productName;

	/** 产品参数. */
	private String productParameter;

	/** The set of 产品规格表. */
	private List<ProductSpec> productList = new ArrayList<>();

	/**
	 * Set the 产品型号.
	 * 
	 * @param productModel
	 *            产品型号
	 */
	public void setProductModel(String productModel) {
		this.productModel = productModel;
	}

	public List<ProductSpec> getProductList() {
		return productList;
	}

	public void setProductList(List<ProductSpec> productList) {
		this.productList = productList;
	}

	/**
	 * Get the 产品型号.
	 * 
	 * @return 产品型号
	 */
	public String getProductModel() {
		return this.productModel;
	}

	/**
	 * Set the 产品类型表.
	 * 
	 * @param productType
	 *            产品类型表
	 */
	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	/**
	 * Get the 产品类型表.
	 * 
	 * @return 产品类型表
	 */
	public ProductType getProductType() {
		return this.productType;
	}

	/**
	 * Set the 产品名称.
	 * 
	 * @param productName
	 *            产品名称
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * Get the 产品名称.
	 * 
	 * @return 产品名称
	 */
	public String getProductName() {
		return this.productName;
	}

	/**
	 * Set the 产品参数.
	 * 
	 * @param productParameter
	 *            产品参数
	 */
	public void setProductParameter(String productParameter) {
		this.productParameter = productParameter;
	}

	/**
	 * Get the 产品参数.
	 * 
	 * @return 产品参数
	 */
	public String getProductParameter() {
		return this.productParameter;
	}

	/**
	 * Add the 产品规格表.
	 * 
	 * @param productSpec
	 *            产品规格表
	 */
	public void addProductSpec(ProductSpec productSpec) {
		this.productList.add(productSpec);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productModel == null) ? 0 : productModel.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (productModel == null) {
			if (other.productModel != null) {
				return false;
			}
		} else if (!productModel.equals(other.productModel)) {
			return false;
		}
		return true;
	}

}
